version: '3.9'

services:
  go:
    build: # Use the Dockerfile from the current directory to build container.
      context: ./app
    container_name: go
    ports: 
      - "9090:9090"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: my-secret-pw
      MYSQL_DATABASE: my-db
    depends_on: 
      - "db"
  
  db:
    image: mysql:latest # use latest version of mysql
    container_name: db # add a name for the container
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment: # add default values, see docs for more info.
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: my-db
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3306:3306'
 
volumes: # add volume to persist data.
  my-db: