- name: Install and configure Jenkins
  hosts: jenkins
  gather_facts: no
  roles:
    - jenkins
    - docker-aws

- name: Install and configure sonarqube
  hosts: sonarqube
  gather_facts: no
  roles:
    - postgresql
    - sonar
